sudo: false
language: java
cache:
  directories:
  - "$HOME/.cache"
services:
- docker
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean install site"
  skip_cleanup: true
  on:
    tags: false
    
notifications:
  email:
    recipients:
    - abhiesa@outlook.com
    on_success: change
    on_failure: always
