spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kubepay/config-dev.git
#        native:
#          search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}